spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  profiles:
    active: local
  cloud:
    config:
      uri: ${CONFIG_URI:http://localhost:8888}
      password: ${CONFIG_PASSWORD:ff6e045a-f86d-401e-96bf-bfe654add3be}
      username: user

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    reactor.netty: DEBUG
