spring:
  application:
    name: gateway
  profiles:
    active: local  # Activate local profile to load gateway-local.yml from config server
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: 'configserver:'

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    reactor.netty: DEBUG
