spring:
  application:
    name: auth
  profiles:
    active: local
  config:
    import: 'optional:configserver:http://localhost:8888'
  cloud:
    config:
      uri: ${CONFIG_URI:http://localhost:8888}
      username: user
      password: ${CONFIG_PASSWORD:nimadirxavfsizlik}