spring:
  application:
    name: task
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: 'configserver:'

  profiles:
    active: local

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    reactor.netty: DEBUG