services:
  hosts:
    gateway: http://localhost:8080
    auth: http://localhost:8081
    organization: http://localhost:8082
    task: http://localhost:8083
    file: http://localhost:8084

  ports:
    gateway: 8080
    auth: 8081
    organization: 8082
    task: 8083
    file: 8084

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${services.hosts.auth}
        user-info-uri: ${services.hosts.auth}/internal/user-info