server:
  port: ${services.ports.gateway}
spring:
  data:
    mongodb:
      uri: mongodb://localhost/gateway
      auto-index-creation: true
  cloud:
    gateway:
      restricted-paths:
        - /api/v1/[a-zA-Z]+/internal/.*
      global-filter:
        - LoggingGlobalFilter
        - RestrictedPathFilter
      routes:
        - id: organization-route
          uri: ${services.hosts.organization}
          predicates:
            - Path=/api/v1/organization/**
          filters:
            - RewritePath=/api/v1/organization(?<remaining>/?.*), /${remaining}

        - id: auth-route
          uri: ${services.hosts.auth}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth(?<remaining>/?.*), /${remaining}



