server:
  port: ${services.ports.organization}
spring:
  application:
    name: organization

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PG_URL:jdbc:postgresql://localhost:5432/viora_db}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:admin}
    hikari:
      schema: organization
    jpa:
      open-in-view: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: organization
    hibernate:
      ddl-auto: update

    show-sql: true
