server:
  port: ${services.ports.organization}
spring:
  application:
    name: organization

  datasource:
    url: jdbc:postgresql://localhost:5432/team
    username: postgres
    password: root123

  jpa:
    properties:
      hibernate:
        default_schema: organizations

    hibernate:
      ddl-auto: update

    show-sql: true
