#server:
#  port: ${services.ports.product}
#
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: ${PG_URL:jdbc:postgresql://localhost:5432/ssvv}
#    username: ${PG_USER:postgres}
#    password: ${PG_PASSWORD:admin}
#    hikari:
#      schema: product
#  jpa:
#    open-in-view: false
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        default_schema: product
#    hibernate:
#      ddl-auto: update

#TODO bu namuna